openapi: '3.0.2'
info:
  title: Mealbot API
  version: '1.0'
servers:
  - url: TODO
paths:
  /api/loan/{Payer}/{Payee}/{Debt}:
    post:
      responses:
        200:
          description: OK
          headers:
            x-mealbot-bad-request:
              allowEmptyValue: false
              schema:
                type: number
                enum:
                  - 1: Not enough arguments
                  - 2: Invalid Debt Value
                  - 5: Other
              required: true
      summary: Adds a value specified by the corresponding parameter to the database
      parameters:
        - in: path
          required: true
          name: Payer
          example: "dede"
          allowEmptyValue: false
          description: Alias of the user that will recieve meal tokens
          schema:
            pattern: "[A-Za-z]+"
            type: string
        - in: path
          required: true
          name: Payee
          example: "dede"
          allowEmptyValue: false
          description: Alias of the user that will give meal tokens
          schema:
            pattern: "[A-Za-z]+"
            type: string
        - in: path
          required: true
          name: Debt
          example: 1
          allowEmptyValue: false
          description: Amount of meal tokens to loan to Payer
          schema:
            type: number
            minimum: 1
  /api/pay/{Payer}/{Payee}/{Payment}:
    post:
      responses:
        200:
          description: 'OK'
        400:
          description: |
            One of:
              An underflow would occur if the payment were to be processed
              The payer does not have a debt to a payee
          headers:
            x-mealbot-bad-request:
              allowEmptyValue: false
              schema:
                type: number
                enum:
                  - 1: Not enough arguments
                  - 2: Invalid Payment Value
                  - 3: Underflow
                  - 4: No Debt between Payer/Payee
                  - 5: Other
              required: true
      parameters:
        - in: path
          required: true
          name: Payer
          example: "dede"
          allowEmptyValue: false
          description: Alias of the user that will give meal tokens
          schema:
            pattern: "[A-Za-z]+"
            type: string
        - in: path
          required: true
          name: Payee
          example: "dede"
          allowEmptyValue: false
          description: Alias of the user that will recieve meal tokens
          schema:
            pattern: "[A-Za-z]+"
            type: string
        - in: path
          required: true
          name: Debt
          example: 1
          allowEmptyValue: false
          description: Amount of meal tokens to pay to Payee
          schema:
            type: number
            minimum: 1
  /api/debt:
    get:
      responses:
        200:
          description: 'OK'
      parameters:
        - in: query
          required: true
          name: User
          allowEmptyValue: false
          description: User to check debt of
          example: dede
          schema:
            type: string
            pattern: "[A-Za-z]+"
      

